version: '3.7'
services: 
  

  server:
    build: ./server
    restart: unless-stopped
    env_file: 
      - ./.env
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_URI}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_ID=${JWT_SECRET}
    networks:
      - backend
      - frontend

  client:
    depends_on: 
      - server
    build:
      context: ./client
    ports: 
      - 3000:3000
    networks:
      - frontend

networks:
  backend:
  frontend:


